version: '2.4'

services:
  flashforge-api:
    build:
      context: .
    container_name: flashforge-api
    ports:
      - "5001:5000"

    # Quotas
    mem_limit: 200m
    cpus: 0.25

    restart: 'unless-stopped'
